/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6753. Copyright MediaTek Inc. (C) 2013.
 * Sun Sep 11 02:21:42 2016
 * Do Not Modify the File.
 */

#ifndef _CUST_I2C_H
#define _CUST_I2C_H


#define I2C_CHANNEL_0					0
#define I2C_CHANNEL_1					1
#define I2C_CHANNEL_2					2
#define I2C_CHANNEL_3					3
#define I2C_CHANNEL_4					4


#define I2C_CAMERA_MAIN_AUTO_DETECT			FALSE
#define I2C_CAMERA_MAIN_CHANNEL				I2C_CHANNEL_0
#define I2C_CAMERA_MAIN_SLAVE_7_BIT_ADDR		0x10


#define I2C_CAMERA_MAIN_AF_AUTO_DETECT			FALSE
#define I2C_CAMERA_MAIN_AF_CHANNEL				I2C_CHANNEL_0
#define I2C_CAMERA_MAIN_AF_SLAVE_7_BIT_ADDR		0x0C


/* M1612 live DT: camera_sub = i2c0 @0x3c (bus/i2c@11007000/camera_sub@3c);
 * m2note had 0x36. */
#define I2C_CAMERA_SUB_AUTO_DETECT			FALSE
#define I2C_CAMERA_SUB_CHANNEL				I2C_CHANNEL_0
#define I2C_CAMERA_SUB_SLAVE_7_BIT_ADDR		0x3C


/* M1612 live DT: strobe_main (LM3644) = i2c2 @0x63
 * (bus/i2c@11009000/strobe_main@63); m2note had i2c3. */
#define I2C_STROBE_MAIN_AUTO_DETECT			FALSE
#define I2C_STROBE_MAIN_CHANNEL				I2C_CHANNEL_2
#define I2C_STROBE_MAIN_SLAVE_7_BIT_ADDR		0x63


/* M1612 live DT: msensor qmcX983 = i2c2 @0x2d (bus/i2c@11009000/msensor@2d,
 * cust_mag@0); m2note had 0x0D. */
#define I2C_MSENSOR_AUTO_DETECT			FALSE
#define I2C_MSENSOR_CHANNEL				I2C_CHANNEL_2
#define I2C_MSENSOR_SLAVE_7_BIT_ADDR		0x2D


#define I2C_GYRO_AUTO_DETECT			FALSE
#define I2C_GYRO_CHANNEL				I2C_CHANNEL_2
#define I2C_GYRO_SLAVE_7_BIT_ADDR		0x68


/* M1612 live DT: gsensor MC3413 = i2c2 @0x4c
 * (bus/i2c@11009000/gsensor_mc3413p@4c, cust_accel@1 mediatek,mc3410,
 * confirmed by live probe); m2note had 0x6A. */
#define I2C_GSENSOR_AUTO_DETECT			FALSE
#define I2C_GSENSOR_CHANNEL				I2C_CHANNEL_2
#define I2C_GSENSOR_SLAVE_7_BIT_ADDR		0x4C


#define I2C_NFC_AUTO_DETECT			FALSE
#define I2C_NFC_CHANNEL				I2C_CHANNEL_2
#define I2C_NFC_SLAVE_7_BIT_ADDR		0x28


/* M1612 live DT: LCD bias chip = i2c1 @0x3e (bus/i2c@11008000/i2c_lcd_bias@3e,
 * confirmed alive by i2c probe); m2note had i2c2 @0x63 (on M1612 i2c2@0x63 is
 * the strobe). Enable line is GPIO119 (bus/lcmbiasenable). */
#define I2C_I2C_LCD_BIAS_AUTO_DETECT			FALSE
#define I2C_I2C_LCD_BIAS_CHANNEL				I2C_CHANNEL_1
#define I2C_I2C_LCD_BIAS_SLAVE_7_BIT_ADDR		0x3E


/* M1612 live DT: touch = i2c1 @0x38 (bus/i2c@11008000/cap_touch@38, FT5x26;
 * co-layout cap_touch_gt@5d); m2note had channel 3 with empty address. */
#define I2C_CAP_TOUCH_AUTO_DETECT			TRUE
#define I2C_CAP_TOUCH_CHANNEL				I2C_CHANNEL_1
#define I2C_CAP_TOUCH_SLAVE_7_BIT_ADDR		0x38


/* M1612 live DT: switching charger BQ25890 = i2c1 @0x6b
 * (bus/i2c@11008000/swithing_charger@6b, chip confirmed by live probe;
 * co-layout swithing_charger_rt9466@53). Not present in m2note DCT. */
#define I2C_SWITHING_CHARGER_AUTO_DETECT			FALSE
#define I2C_SWITHING_CHARGER_CHANNEL				I2C_CHANNEL_1
#define I2C_SWITHING_CHARGER_SLAVE_7_BIT_ADDR		0x6B


/* M1612 live DT: ext_buck = i2c4 @0x6b (bus/i2c@11012000/ext_buck@6b,
 * matches live probe bus4 = ext_buck@0x6b; chip model unknown - needs stock
 * LK/vmlinux). Not present in m2note DCT. */
#define I2C_EXT_BUCK_AUTO_DETECT			FALSE
#define I2C_EXT_BUCK_CHANNEL				I2C_CHANNEL_4
#define I2C_EXT_BUCK_SLAVE_7_BIT_ADDR		0x6B


#endif /* _CUST_I2C_H */
