/*
 * Generated by MTK SP DrvGen Version 03.13.6 for MT6753. Copyright MediaTek Inc. (C) 2013.
 * Sun Sep 11 02:21:42 2016
 * Do Not Modify the File.
 */

#ifndef __CUST_EINTH
#define __CUST_EINTH
#ifdef __cplusplus
extern "C" {
#endif
#define CUST_EINTF_TRIGGER_RISING     			1    //High Polarity and Edge Sensitive
#define CUST_EINTF_TRIGGER_FALLING    			2    //Low Polarity and Edge Sensitive
#define CUST_EINTF_TRIGGER_HIGH      				4    //High Polarity and Level Sensitive
#define CUST_EINTF_TRIGGER_LOW       				8    //Low Polarity and Level Sensitive
#define CUST_EINT_DEBOUNCE_DISABLE          0
#define CUST_EINT_DEBOUNCE_ENABLE           1
//////////////////////////////////////////////////////////////////////////////


#define CUST_EINT_MSDC1_INS_NUM              5
#define CUST_EINT_MSDC1_INS_DEBOUNCE_CN      1
#define CUST_EINT_MSDC1_INS_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_MSDC1_INS_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_ENABLE

/* M1612 live DT: ACCDET = EINT6 (bus/accdet@ interrupts = <6 8>,
 * debounce = <6 256000>); m2note had EINT9 (= SIM2 hot-plug on M1612). */
#define CUST_EINT_ACCDET_NUM              6
#define CUST_EINT_ACCDET_DEBOUNCE_CN      256
#define CUST_EINT_ACCDET_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_ACCDET_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_ENABLE

#define CUST_EINT_TOUCH_NUM              10
#define CUST_EINT_TOUCH_DEBOUNCE_CN      0
#define CUST_EINT_TOUCH_TYPE							CUST_EINTF_TRIGGER_FALLING
#define CUST_EINT_TOUCH_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

/* M1612: m2note ACCEL_GYRO_INT1/2 (EINT11/12) removed - live GPIO11/12 are
 * sub cam rst/pnd (bus/pinctrl/cam1@0..3); MC3413 accel has no irq in DT. */

/* M1612: ALS/PS int = EINT1/GPIO1 (bus/pinctrl/alspspincfg pins = 0x100,
 * PA22x, polling_mode_ps=0). INFERENCE: EINT number - live als_ps node has
 * no explicit interrupts property. m2note had EINT18. */
#define CUST_EINT_ALS_NUM              1
#define CUST_EINT_ALS_DEBOUNCE_CN      0
#define CUST_EINT_ALS_TYPE							CUST_EINTF_TRIGGER_LOW
#define CUST_EINT_ALS_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

/* M1612: m2note SWTP (EINT88) removed - no swtp node in live DT
 * (cp128_eint and hall_1 both disabled in stock). */

/* M1612: NFC irq pin = GPIO2 (bus/pinctrl/state_irq_init pins = 0x200);
 * INFERENCE: EINT2 (direct-mapped). m2note had EINT144. NFC disabled. */
#define CUST_EINT_NFC_NUM              2
#define CUST_EINT_NFC_DEBOUNCE_CN      0
#define CUST_EINT_NFC_TYPE							CUST_EINTF_TRIGGER_HIGH
#define CUST_EINT_NFC_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

#define CUST_EINT_DSI_TE_1_NUM              147
#define CUST_EINT_DSI_TE_1_DEBOUNCE_CN      0
#define CUST_EINT_DSI_TE_1_TYPE							CUST_EINTF_TRIGGER_RISING
#define CUST_EINT_DSI_TE_1_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE

/* M1612 live DT: fingerprint (Goodix SPI) irq = EINT124, edge falling
 * (bus/fingerprint@ interrupts = <124 2>, debounce 0). */
#define CUST_EINT_FINGERPRINT_NUM              124
#define CUST_EINT_FINGERPRINT_DEBOUNCE_CN      0
#define CUST_EINT_FINGERPRINT_TYPE							CUST_EINTF_TRIGGER_FALLING
#define CUST_EINT_FINGERPRINT_DEBOUNCE_EN      CUST_EINT_DEBOUNCE_DISABLE



//////////////////////////////////////////////////////////////////////////////
#ifdef __cplusplus
}
#endif
#endif //_CUST_EINT_H


