#
# Makefile for misc devices that really don't fit anywhere else.
#
include $(srctree)/drivers/misc/mediatek/Makefile.custom

CFLAGS_nt35596_fhd_dsi_vdo_auo.o += -Wno-unused-function -Wno-return-type
obj-y += nt35596_fhd_dsi_vdo_auo.o




