#
# Makefile for misc devices that really don't fit anywhere else.
#
-include $(srctree)/drivers/misc/mediatek/Makefile.custom

CFLAGS_nt35532_fhd_dsi_vdo_sharp.o += -Wno-error=unused-function
CFLAGS_nt35532_fhd_dsi_vdo_sharp.o += -Wno-error=unused-variable

obj-y += nt35532_fhd_dsi_vdo_sharp.o




