include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -Wno-error=strict-prototypes
ccflags-y += -Wno-error=unused-variable
ccflags-y += -Wno-error=unused-function
ccflags-y += -Wno-error=format
ccflags-y += -Wno-error=return-type
obj-y += s5k3l2xxmipiraw_Sensor.o

