include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -Wno-error
ccflags-y += -Wno-error=unused-function -Wno-error=unused-variable
ccflags-y += -Wno-error=strict-prototypes -Wno-error=declaration-after-statement
ccflags-y += -Wno-error=format-extra-args
obj-y += s5k3l2xxliteonmipiraw_Sensor.o
